# Generated by Django 4.2 on 2023-12-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={"ordering": ("first_name", "last_name")},
        ),
        migrations.AddField(
            model_name="flight",
            name="crew",
            field=models.ManyToManyField(
                blank=True, related_name="flights", to="flights.crew"
            ),
        ),
        migrations.AlterField(
            model_name="airplanetype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
